// generated by stringer -type ItemType; DO NOT EDIT

package dcmnet

import "fmt"

const (
	_ItemType_name_0 = "ApplicationContext"
	_ItemType_name_1 = "RequestPresentationContextAcceptPresentationContext"
	_ItemType_name_2 = "AbstractSyntax"
	_ItemType_name_3 = "TransferSyntax"
	_ItemType_name_4 = "UserInfoMaxPDULengthImplementationClassUIDAsyncOperationsRoleSelectionImplementationVersion"
)

var (
	_ItemType_index_0 = [...]uint8{0, 18}
	_ItemType_index_1 = [...]uint8{0, 26, 51}
	_ItemType_index_2 = [...]uint8{0, 14}
	_ItemType_index_3 = [...]uint8{0, 14}
	_ItemType_index_4 = [...]uint8{0, 8, 20, 42, 57, 70, 91}
)

func (i ItemType) String() string {
	switch {
	case i == 16:
		return _ItemType_name_0
	case 32 <= i && i <= 33:
		i -= 32
		return _ItemType_name_1[_ItemType_index_1[i]:_ItemType_index_1[i+1]]
	case i == 48:
		return _ItemType_name_2
	case i == 64:
		return _ItemType_name_3
	case 80 <= i && i <= 85:
		i -= 80
		return _ItemType_name_4[_ItemType_index_4[i]:_ItemType_index_4[i+1]]
	default:
		return fmt.Sprintf("ItemType(%d)", i)
	}
}
