// generated by stringer -type PCResult; DO NOT EDIT

package dcmnet

import "fmt"

const _PCResult_name = "PCAcceptancePCUserRejectionPCProviderRejectionNoReasonPCProviderRejectionAbstractSyntaxNotSupportedPCProviderRejectionTransferSyntaxesNotSupported"

var _PCResult_index = [...]uint8{0, 12, 27, 54, 99, 146}

func (i PCResult) String() string {
	if i >= PCResult(len(_PCResult_index)-1) {
		return fmt.Sprintf("PCResult(%d)", i)
	}
	return _PCResult_name[_PCResult_index[i]:_PCResult_index[i+1]]
}
