// generated by stringer -type PDUType; DO NOT EDIT

package dcmnet

import "fmt"

const _PDUType_name = "PDUAssociateRQPDUAssociateACPDUAssociateRJPDUPresentationDataPDUReleaseRQPDUReleaseRPPDUAbort"

var _PDUType_index = [...]uint8{0, 14, 28, 42, 61, 73, 85, 93}

func (i PDUType) String() string {
	i -= 1
	if i >= PDUType(len(_PDUType_index)-1) {
		return fmt.Sprintf("PDUType(%d)", i+1)
	}
	return _PDUType_name[_PDUType_index[i]:_PDUType_index[i+1]]
}
