// generated by stringer -type PDVType; DO NOT EDIT

package dcmnet

import "fmt"

const _PDVType_name = "DataCommand"

var _PDVType_index = [...]uint8{0, 4, 11}

func (i PDVType) String() string {
	if i >= PDVType(len(_PDVType_index)-1) {
		return fmt.Sprintf("PDVType(%d)", i)
	}
	return _PDVType_name[_PDVType_index[i]:_PDVType_index[i+1]]
}
